import type { ZoneId } from '@/components/ship/ShipDiagram'

export interface Product {
  id: string
  slug: string
  name: { en: string; pl: string; de: string }
  shortDesc: { en: string; pl: string; de: string }
  description: { en: string; pl: string; de: string }
  zones: ZoneId[]
  tags: string[]
  isBiological: boolean
  dosage: { baseConc: number; unit: 'ml/L' | '%' | 'g/L'; notesEn: string }
  category: string
  image: string
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1', slug: 'air-cooler-cleaner',
    name: { en: 'DG Air Cooler Cleaner', pl: 'DG Air Cooler Cleaner', de: 'DG Air Cooler Cleaner' },
    shortDesc: {
      en: 'Heavy-duty degreasing solution for diesel engine charge air coolers and turbochargers.',
      pl: 'Silny środek odtłuszczający do chłodnic powietrza doładowania i turbosprężarek.',
      de: 'Schwerlast-Entfettungslösung für Ladeluftkühler und Turbolader von Dieselmotoren.',
    },
    description: {
      en: 'DG Air Cooler Cleaner is a water-based heavy-duty degreasing solution for diesel engine charge air coolers and turbochargers. It dissolves lube-oil and fuel-oil deposits as well as contamination entering through the air inlet. Suitable for all diesel engine types via spray or bath application. Available as 25 L concentrate.',
      pl: 'DG Air Cooler Cleaner to wodny środek odtłuszczający do chłodnic powietrza doładowania i turbosprężarek. Skutecznie usuwa osady olejowe i paliwowe. Dwie metody aplikacji: wtrysk/natrysk lub kąpiel myjąca. Dostępny jako koncentrat 25 L.',
      de: 'DG Air Cooler Cleaner ist eine wasserbasierte Schwerlast-Entfettungslösung für Ladeluftkühler und Turbolader. Löst Öl- und Kraftstoffablagerungen. Zwei Anwendungsmethoden: Einspritzung/Sprühen oder Tauchbad. Erhältlich als 25-L-Konzentrat.',
    },
    zones: ['cooling', 'engine_room'],
    tags: ['air cooler', 'turbocharger', 'degreaser', 'engine', 'charge air', 'diesel'],
    isBiological: false,
    dosage: { baseConc: 20, unit: 'ml/L', notesEn: 'Dilute 10–30% for spray/injection; use undiluted for bath cleaning.' },
    category: 'Cooling',
    image: '/products/Air Cooler Cleaner 25L_niebieska.jpg',
  },
  {
    id: '2', slug: 'alkal-control',
    name: { en: 'DG Alkal Control', pl: 'DG Alkal Control', de: 'DG Alkal Control' },
    shortDesc: {
      en: 'Concentrated alkaline treatment for maintaining optimal alkalinity in boiler water.',
      pl: 'Skoncentrowany preparat alkaliczny do utrzymywania optymalnej zasadowości wody kotłowej.',
      de: 'Konzentriertes alkalisches Mittel zur Aufrechterhaltung optimaler Alkalität im Kesselspeisewasser.',
    },
    description: {
      en: 'DG Alkal Control is a concentrated liquid alkaline treatment for maintaining optimal alkalinity in boiler water. It prevents calcium and magnesium scale build-up and protects against corrosion caused by acidic gases. Compatible with all pressure ratings; also used as a neutraliser after acid cleaning.',
      pl: 'DG Alkal Control to skoncentrowany preparat alkaliczny utrzymujący optymalną zasadowość wody kotłowej. Zapobiega osadzaniu się kamienia i chroni przed korozją. Kompatybilny ze wszystkimi ciśnieniami; stosowany jako neutralizator po czyszczeniu kwasem.',
      de: 'DG Alkal Control ist ein konzentriertes alkalisches Mittel zur Aufrechterhaltung optimaler Alkalität im Kesselspeisewasser. Verhindert Kalk- und Korrosionsablagerungen. Kompatibel mit allen Druckstufen.',
    },
    zones: ['engine_room'],
    tags: ['boiler', 'alkalinity', 'water treatment', 'scale', 'corrosion', 'neutraliser'],
    isBiological: false,
    dosage: { baseConc: 5, unit: 'ml/L', notesEn: 'Dose to maintain pH 10.5–11.5 in boiler water.' },
    category: 'Engine Room',
    image: '/products/Alkal Control 25L_biała.jpg',
  },
  {
    id: '3', slug: 'anti-sludge-agent',
    name: { en: 'DG Anti-Sludge Agent', pl: 'DG Anti-Sludge Agent', de: 'DG Anti-Sludge Agent' },
    shortDesc: {
      en: 'Self-dispersing fuel oil treatment that stabilises fuel blends and eliminates heavy fuel sludge.',
      pl: 'Samodyspergujący preparat paliwowy stabilizujący mieszanki i eliminujący szlam w ciężkich paliwach.',
      de: 'Selbstdispergierendes Heizölbehandlungsmittel zur Stabilisierung von Kraftstoffmischungen.',
    },
    description: {
      en: 'DG Anti-Sludge Agent is a self-dispersing fuel oil treatment that stabilises fuel blends and eliminates compatibility issues in heavy fuels. It disperses existing sludge deposits and prevents new formation, while combating microorganisms in fuel tanks. Dose directly into the bunker tank at 1:4000 initially.',
      pl: 'DG Anti-Sludge Agent stabilizuje mieszanki paliwowe i dysperguje istniejące osady w ciężkich paliwach. Zapobiega tworzeniu się nowych osadów i zwalcza mikroorganizmy. Dozować do zbiornika bunkrowego w proporcji 1:4000.',
      de: 'DG Anti-Sludge Agent stabilisiert Kraftstoffmischungen und dispergiert vorhandene Schlammablagerungen. Verhindert Neubildung und bekämpft Mikroorganismen. Erstdosierung 1:4000.',
    },
    zones: ['engine_room', 'fuel'],
    tags: ['fuel', 'sludge', 'bunker', 'heavy fuel', 'separator', 'stabiliser'],
    isBiological: false,
    dosage: { baseConc: 0.25, unit: 'ml/L', notesEn: 'Initial dose 1:4000 into bunker tank; maintenance 1:8000.' },
    category: 'Fuel',
    image: '/products/Anti-Sludge Agent 25L_czerwona.jpg',
  },
  {
    id: '4', slug: 'anti-fouling-agent',
    name: { en: 'DG Anti-Fouling Agent', pl: 'DG Anti-Fouling Agent', de: 'DG Anti-Fouling Agent' },
    shortDesc: {
      en: 'Protects seawater cooling systems against biofouling and corrosion by marine microorganisms.',
      pl: 'Chroni układy chłodzenia wodą morską przed biozarastaniem i korozją przez mikroorganizmy morskie.',
      de: 'Schützt Seekühlsysteme vor Bewuchs und Korrosion durch marine Mikroorganismen.',
    },
    description: {
      en: 'DG Anti-Fouling Agent protects seawater cooling systems against biofouling and corrosion. It prevents the growth of marine microorganisms and algae on internal surfaces while acting as a corrosion inhibitor. Dose at 0.5 litres per 100 tonnes of seawater flow per hour.',
      pl: 'DG Anti-Fouling Agent chroni układy chłodzenia wodą morską przed biozarastaniem i korozją. Zapobiega namnażaniu się mikroorganizmów i glonów. Dozować 0,5 L na 100 t/h przepływu wody morskiej.',
      de: 'DG Anti-Fouling Agent schützt Seekühlsysteme vor Bewuchs und Korrosion. Verhindert Wachstum von Mikroorganismen und Algen. Dosierung: 0,5 L pro 100 t/h Seewasserdurchfluss.',
    },
    zones: ['cooling', 'ballast_tank'],
    tags: ['antifouling', 'seawater', 'cooling', 'biofouling', 'corrosion inhibitor', 'algae'],
    isBiological: false,
    dosage: { baseConc: 5, unit: 'ml/L', notesEn: '0.5 L per 100 tonnes of seawater flow per hour.' },
    category: 'Cooling',
    image: '/products/Anti-Fouling Agent 25L_biała.jpg',
  },
  {
    id: '5', slug: 'antifreeze-el',
    name: { en: 'DG Antifreeze/Coolant EL', pl: 'DG Antifreeze/Coolant EL', de: 'DG Antifreeze/Coolant EL' },
    shortDesc: {
      en: 'Premium long-life coolant with OAT technology providing freeze protection down to -37°C.',
      pl: 'Płyn chłodniczy długiego działania z technologią OAT chroniący do -37°C.',
      de: 'Premium-Langzeitkühlmittel mit OAT-Technologie, Frostschutz bis -37°C.',
    },
    description: {
      en: 'DG Antifreeze/Coolant EL is a premium long-life coolant based on Mono Ethylene Glycol with OAT technology, providing protection against temperature extremes, rust, corrosion, and scale formation. Freeze protection down to -37°C. Change only with engine completely cold. Available as 25 L concentrate.',
      pl: 'DG Antifreeze/Coolant EL to wysokiej jakości płyn chłodniczy długiego działania oparty na MEG z technologią OAT. Ochrona przed zamarzaniem do -37°C oraz zabezpieczenie przed korozją i osadem. Wymieniać wyłącznie przy zimnym silniku.',
      de: 'DG Antifreeze/Coolant EL ist ein Premium-Langzeitkühlmittel auf MEG-Basis mit OAT-Technologie. Frostschutz bis -37°C. Wechsel nur bei vollständig kaltem Motor.',
    },
    zones: ['cooling'],
    tags: ['antifreeze', 'coolant', 'OAT', 'freeze protection', 'corrosion', 'MEG'],
    isBiological: false,
    dosage: { baseConc: 33, unit: '%', notesEn: '33% concentration for -20°C protection; 50% for -37°C.' },
    category: 'Cooling',
    image: '/products/Antifreeze EL 25L_biała.jpg',
  },
  {
    id: '6', slug: 'antifreeze',
    name: { en: 'DG Antifreeze/Coolant', pl: 'DG Antifreeze/Coolant', de: 'DG Antifreeze/Coolant' },
    shortDesc: {
      en: 'Reliable multi-engine coolant with long-lasting inhibitors, freeze protection to -37°C.',
      pl: 'Niezawodny płyn chłodniczy z długotrwałymi inhibitorami, ochrona do -37°C.',
      de: 'Zuverlässiges Kühlmittel mit Langzeitinhibitoren, Frostschutz bis -37°C.',
    },
    description: {
      en: 'DG Antifreeze/Coolant is a reliable multi-engine coolant based on Mono Ethylene Glycol with long-lasting inhibitors protecting against temperature extremes, rust, corrosion, and scale. Freeze protection to -37°C. Always consult manufacturer\'s instructions and change with engine switched off.',
      pl: 'DG Antifreeze/Coolant to niezawodny płyn chłodniczy na bazie MEG z długotrwałymi inhibitorami chroniącymi przed korozją i zamarzaniem do -37°C. Wymieniać wyłącznie przy wyłączonym silniku.',
      de: 'DG Antifreeze/Coolant ist ein zuverlässiges Kühlmittel auf MEG-Basis mit Langzeitinhibitoren. Frostschutz bis -37°C. Wechsel nur bei ausgeschaltetem Motor.',
    },
    zones: ['cooling'],
    tags: ['antifreeze', 'coolant', 'freeze protection', 'corrosion', 'MEG', 'inhibitor'],
    isBiological: false,
    dosage: { baseConc: 33, unit: '%', notesEn: '33% for -20°C; 50% for -37°C protection.' },
    category: 'Cooling',
    image: '/products/Antifreeze 25L_biała.jpg',
  },
  {
    id: '7', slug: 'bilge-cleaner-hd',
    name: { en: 'DG Bilge Cleaner HD', pl: 'DG Bilge Cleaner HD', de: 'DG Bilge Cleaner HD' },
    shortDesc: {
      en: 'Heavy-duty alkaline cleaner for engine rooms and bilge areas at high dilution ratios.',
      pl: 'Silnie zasadowy środek czyszczący do maszynowni i zęz przy wysokich rozcieńczeniach.',
      de: 'Schwerlastalkalischer Reiniger für Maschinenräume und Bilgen bei hohen Verdünnungsraten.',
    },
    description: {
      en: 'DG Bilge Cleaner HD is a heavy-duty alkaline cleaner for engine rooms and bilge areas. Its high-concentration formula combines anionic and non-ionic surfactants delivering effective degreasing at high dilution ratios. Compatible with steam cleaning (1:20–1:100) and immersion (1:10–1:50). Available as 25 L concentrate.',
      pl: 'DG Bilge Cleaner HD to silnie zasadowy środek czyszczący przeznaczony do maszynowni i zęz. Formuła łączy surfaktanty anionowe i niejonowe, zapewniając efektywne odtłuszczanie przy wysokich rozcieńczeniach. Dostępny jako koncentrat 25 L.',
      de: 'DG Bilge Cleaner HD ist ein schwerlastiger alkalischer Reiniger für Maschinenräume und Bilgen. Hochkonzentrierte Formel mit anionischen und nicht-ionischen Tensiden. Kompatibel mit Dampfreinigung (1:20–1:100) und Tauchen (1:10–1:50).',
    },
    zones: ['bilge', 'engine_room'],
    tags: ['bilge', 'degreaser', 'engine room', 'alkaline', 'heavy duty', 'surfactant'],
    isBiological: false,
    dosage: { baseConc: 50, unit: 'ml/L', notesEn: 'Steam cleaning 1:20–1:100; immersion 1:10–1:50.' },
    category: 'Bilge',
    image: '/products/Bilge Cleaner HD krzywe_niebieska.jpg',
  },
  {
    id: '8', slug: 'bilge-water-flocculant-agent',
    name: { en: 'DG Bilge Water Flocculant Agent', pl: 'DG Bilge Water Flocculant Agent', de: 'DG Bilge Water Flocculant Agent' },
    shortDesc: {
      en: 'Iron-free liquid for separating oil residues from bilge water, achieving below 3 ppm oil.',
      pl: 'Bezżelazny preparat do separacji olejów z wód zęzowych, osiągający poniżej 3 ppm oleju.',
      de: 'Eisenfreies Mittel zur Öltrennung aus Bilgenwasser, Ergebnis unter 3 ppm Öl.',
    },
    description: {
      en: 'DG Bilge Water Flocculant Agent is an iron-free, environmentally safe liquid for separating oil residues from bilge water. It breaks oil-in-water emulsions and builds flocs — discharged water typically contains less than 3 ppm oil. Operates across a wide pH range at 50–250 ppm dosage.',
      pl: 'DG Bilge Water Flocculant Agent to bezpieczny dla środowiska preparat do separacji olejów z wód zęzowych. Rozbija emulsje olej-w-wodzie, osiągając zawartość oleju poniżej 3 ppm. Działa w szerokim zakresie pH przy dawce 50–250 ppm.',
      de: 'DG Bilge Water Flocculant Agent ist ein eisenfreies, umweltsicheres Mittel zur Öltrennung aus Bilgenwasser. Bricht Öl-in-Wasser-Emulsionen auf. Dosierung 50–250 ppm, Ergebnis unter 3 ppm Öl.',
    },
    zones: ['bilge'],
    tags: ['bilge water', 'flocculant', 'oil separator', 'oily water', 'MARPOL', 'emulsion'],
    isBiological: false,
    dosage: { baseConc: 0.15, unit: 'ml/L', notesEn: 'Dose 50–250 ppm into bilge water before separation.' },
    category: 'Bilge',
    image: '/products/Bilge Water Flocculant Agent krzywe_biała.jpg',
  },
  {
    id: '9', slug: 'bioactivae-descaling-agent',
    name: { en: 'DG Bioactivae Descaling Agent', pl: 'DG Bioactivae Descaling Agent', de: 'DG Bioactivae Descaling Agent' },
    shortDesc: {
      en: 'Non-hazardous organic acids and enzymes concentrate for removing scale, rust and biological deposits.',
      pl: 'Nieszkodliwy koncentrat kwasów organicznych i enzymów do usuwania kamienia, rdzy i osadów biologicznych.',
      de: 'Ungefährliches Konzentrat aus organischen Säuren und Enzymen zur Entfernung von Kalk und Rost.',
    },
    description: {
      en: 'DG Bioactivae Descaling Agent is a non-hazardous concentrate of organic acids, enzymes, and corrosion inhibitors for removing scale, lime, rust, algae, and biological deposits from water systems. Non-corrosive and non-flammable. Optimal bath cleaning temperature 45–65°C. Available as 25 L concentrate.',
      pl: 'DG Bioactivae Descaling Agent to nieszkodliwy koncentrat kwasów organicznych i enzymów do usuwania kamienia, rdzy, glonów i osadów biologicznych. Niekorozyjny i niepalny. Optymalna temperatura kąpieli: 45–65°C. Koncentrat 25 L.',
      de: 'DG Bioactivae Descaling Agent ist ein ungefährliches Konzentrat aus organischen Säuren, Enzymen und Korrosionsinhibitoren. Entfernt Kalk, Rost, Algen und biologische Ablagerungen. Optimale Badtemperatur: 45–65°C.',
    },
    zones: ['cooling', 'engine_room'],
    tags: ['descaling', 'enzyme', 'biological', 'scale', 'lime', 'organic acid'],
    isBiological: true,
    dosage: { baseConc: 10, unit: '%', notesEn: 'Use 10–30% solution at 45–65°C. Rinse thoroughly after.' },
    category: 'Biological',
    image: '/products/bio/Bioactivae Descaling Agent 25L_zielony.jpg',
  },
  {
    id: '10', slug: 'biver-hd',
    name: { en: 'DG Biver HD', pl: 'DG Biver HD', de: 'DG Biver HD' },
    shortDesc: {
      en: 'Highly concentrated alkaline cleaner with potassium hydroxide for oils, fats and carbon deposits.',
      pl: 'Mocno skoncentrowany alkaliczny środek z wodorotlenkiem potasu do olejów, tłuszczów i osadów węglowych.',
      de: 'Hochkonzentrierter alkalischer Reiniger mit Kaliumhydroxid für Öle, Fette und Kohlenstoff.',
    },
    description: {
      en: 'DG Biver HD is a powerful highly concentrated alkaline cleaner with anionic and non-ionic surfactants and potassium hydroxide. Removes vegetable, fish, and animal oils and fats, greases, soot, and carbon deposits. Very high dilution ratios: 10–25% for spray, 1:10–1:50 for immersion, 1:20–1:100 for steam.',
      pl: 'DG Biver HD to mocno skoncentrowany alkaliczny środek czyszczący z surfaktantami i wodorotlenkiem potasu. Usuwa oleje, tłuszcze, sadzę i osady węglowe przy bardzo wysokich rozcieńczeniach.',
      de: 'DG Biver HD ist ein hochkonzentrierter alkalischer Reiniger mit Kaliumhydroxid. Entfernt Öle, Fette, Ruß und Kohlenstoffablagerungen. Hohe Verdünnungsraten: 10–25% Sprühen, 1:10–1:50 Eintauchen.',
    },
    zones: ['engine_room', 'cargo_hold'],
    tags: ['alkaline cleaner', 'degreaser', 'cargo', 'heavy duty', 'potassium hydroxide', 'soot'],
    isBiological: false,
    dosage: { baseConc: 20, unit: 'ml/L', notesEn: 'Spray 10–25%; immersion 1:10–1:50; steam 1:20–1:100.' },
    category: 'Engine Room',
    image: '/products/Biver HD 25L_niebieska.jpg',
  },
  {
    id: '11', slug: 'boiler-sludge-coagulant',
    name: { en: 'DG Boiler Sludge Coagulant', pl: 'DG Boiler Sludge Coagulant', de: 'DG Boiler Sludge Coagulant' },
    shortDesc: {
      en: 'Prevents sludge build-up on boiler surfaces by dispersing deposits for removal through blowdown.',
      pl: 'Zapobiega osadzaniu szlamu w kotłach, kondycjonując go do usunięcia przez blowdown.',
      de: 'Verhindert Schlammablagerungen in Kesseln durch Dispergierung für die Entfernung durch Abschlämmen.',
    },
    description: {
      en: 'DG Boiler Sludge Coagulant prevents sludge and deposit build-up on internal boiler surfaces by dispersing sludge for removal through blowdown. Also handles minor oil contamination through coagulation. Used alongside standard boiler water treatment programmes. Available as 25 L concentrate.',
      pl: 'DG Boiler Sludge Coagulant zapobiega osadzaniu szlamu na powierzchniach kotłów, kondycjonując go do usunięcia przez blowdown. Radzi sobie z niewielkim zanieczyszczeniem olejem. Stosowany ze standardowymi preparatami kotłowymi.',
      de: 'DG Boiler Sludge Coagulant verhindert Schlammablagerungen in Kesseln durch Dispergierung für die Entfernung durch Abschlämmen. Ergänzt Standard-Kesselwasserbehandlungsprogramme.',
    },
    zones: ['engine_room'],
    tags: ['boiler', 'sludge', 'coagulant', 'water treatment', 'blowdown', 'scale'],
    isBiological: false,
    dosage: { baseConc: 2, unit: 'ml/L', notesEn: 'Dose to maintain residual 30–50 ppm in boiler water.' },
    category: 'Engine Room',
    image: '/products/Boiler Sludge Coagulant 25L_biała.jpg',
  },
  {
    id: '12', slug: 'carbon-remover',
    name: { en: 'DG Carbon Remover', pl: 'DG Carbon Remover', de: 'DG Carbon Remover' },
    shortDesc: {
      en: 'Powerful water-based liquid solvent for fast removal of all types of carbon deposits.',
      pl: 'Silny wodny zmywacz do szybkiego usuwania wszelkich osadów węglowych.',
      de: 'Leistungsstarkes wasserbasiertes Lösemittel zur schnellen Entfernung aller Kohlenstoffablagerungen.',
    },
    description: {
      en: 'DG Carbon Remover is a powerful water-based liquid solvent for fast removal of all types of carbon deposits. Its formula quickly dissolves stubborn buildup without hard scraping. Non-flammable; dilute 1:10 to 1:100 for general use or 1:5 for heavy grease. Available in 25 L concentrate.',
      pl: 'DG Carbon Remover to silny wodny zmywacz do szybkiego usuwania osadów węglowych bez mechanicznego skrobania. Niepalny; rozcieńczenie 1:10 do 1:100 do ogólnego czyszczenia, 1:5 przy silnym zabrudzeniu. Koncentrat 25 L.',
      de: 'DG Carbon Remover ist ein leistungsstarkes wasserbasiertes Lösemittel zur Entfernung aller Kohlenstoffablagerungen ohne Kratzen. Nicht brennbar; Verdünnung 1:10 bis 1:100.',
    },
    zones: ['engine_room'],
    tags: ['carbon', 'deposits', 'degreaser', 'engine', 'solvent', 'non-flammable'],
    isBiological: false,
    dosage: { baseConc: 100, unit: 'ml/L', notesEn: 'Use 1:5 for heavy deposits; 1:10–1:100 general cleaning.' },
    category: 'Engine Room',
    image: '/products/Carbon Remover krzywe_niebieska.jpg',
  },
  {
    id: '13', slug: 'cargo-marine-cleaner-hd',
    name: { en: 'DG Cargo Marine Cleaner HD', pl: 'DG Cargo Marine Cleaner HD', de: 'DG Cargo Marine Cleaner HD' },
    shortDesc: {
      en: 'Alkaline heavy-duty cleaner for cargo holds, highly effective after petcoke and coal cargoes.',
      pl: 'Zasadowy środek heavy-duty do ładowni, wysoce skuteczny po petakoksie i węglu.',
      de: 'Alkalischer Schwerlastenreiniger für Ladefächer, hochwirksam nach Petrocoke und Kohleladungen.',
    },
    description: {
      en: 'DG Cargo Marine Cleaner HD is an alkaline heavy-duty multi-purpose cleaner for cargo holds on bulk carriers. Highly effective after petcoke, coal, and difficult cargoes. Safe on epoxy coatings and free from nonylphenol ethoxylates. Apply as 10% solution, leave 10–15 min, then high-pressure rinse.',
      pl: 'DG Cargo Marine Cleaner HD to zasadowy środek czyszczący do ładowni masowców, skuteczny po przewozie petakoksu i węgla. Bezpieczny dla powłok epoksydowych. Stosować jako 10% roztwór, pozostawić 10–15 minut, spłukać wysokociśnieniowo.',
      de: 'DG Cargo Marine Cleaner HD ist ein alkalischer Schwerlastenreiniger für Schiffsladefächer. Hochwirksam nach Petrocoke- und Kohleladungen. Sicher auf Epoxidbeschichtungen. 10%-Lösung, 10–15 Min. einwirken lassen.',
    },
    zones: ['cargo_hold'],
    tags: ['cargo hold', 'bulk carrier', 'petcoke', 'coal', 'alkaline', 'epoxy safe'],
    isBiological: false,
    dosage: { baseConc: 100, unit: 'ml/L', notesEn: '10% solution; leave 10–15 min; high-pressure rinse.' },
    category: 'Cargo Hold',
    image: '/products/Cargo Marine Cleaner HD krzywe_niebieska.jpg',
  },
  {
    id: '14', slug: 'cementosol',
    name: { en: 'DG Cementosol', pl: 'DG Cementosol', de: 'DG Cementosol' },
    shortDesc: {
      en: 'Strongly acidic liquid remover for cement, concrete, mortar, limescale and rust.',
      pl: 'Silnie kwaśny zmywacz do cementu, betonu, zaprawy, kamienia kotłowego i rdzy.',
      de: 'Stark saures Mittel zur Entfernung von Zement, Beton, Mörtel, Kalk und Rost.',
    },
    description: {
      en: 'DG Cementosol is a concentrated strongly acidic liquid remover for cement, concrete, mortar, limescale, and rust. Effective on glass, walls, floors, and sanitary equipment. Apply undiluted or diluted 1:1 to 1:15; leave 30 seconds to 5 minutes, then rinse. Use on acid-resistant surfaces only.',
      pl: 'DG Cementosol to skoncentrowany kwaśny zmywacz do cementu, betonu, kamienia kotłowego i rdzy. Stosować nierozcieńczony lub rozcieńczony 1:1 do 1:15, pozostawić 30 sek–5 min, spłukać. Wyłącznie na powierzchniach kwasoodpornych.',
      de: 'DG Cementosol ist ein konzentriertes stark saures Mittel zur Entfernung von Zement, Beton, Mörtel, Kalk und Rost. Nur für säurebeständige Oberflächen. Verdünnung 1:1 bis 1:15.',
    },
    zones: ['deck', 'cargo_hold'],
    tags: ['cement', 'concrete', 'descaler', 'rust', 'acid', 'mortar'],
    isBiological: false,
    dosage: { baseConc: 100, unit: 'ml/L', notesEn: 'Undiluted or 1:1–1:15; contact 30 sec to 5 min; rinse.' },
    category: 'Deck',
    image: '/products/Cementosol 25 L krzywe_czarna.jpg',
  },
  {
    id: '15', slug: 'cip-descaler',
    name: { en: 'DG CIP Descaler', pl: 'DG CIP Descaler', de: 'DG CIP Descaler' },
    shortDesc: {
      en: 'Highly concentrated acids and enzymes for removing scale from pipes, heat exchangers and ballast systems.',
      pl: 'Wysoce skoncentrowana mieszanina kwasów i enzymów do usuwania kamienia z rur i wymienników.',
      de: 'Hochkonzentriertes Gemisch aus Säuren und Enzymen zur Entkalkung von Rohren und Wärmetauschern.',
    },
    description: {
      en: 'DG CIP Descaler is a highly concentrated mixture of acids, enzymes, and tensides for removing scale, magnetite, algae, lime, and rust from pipes, plate heat exchangers, separators, and ballast water systems. Non-flammable, low-foaming, biodegradable. Use as 5% solution; monitor pH; rinse after use.',
      pl: 'DG CIP Descaler to wysoce skoncentrowana mieszanina kwasów i enzymów do usuwania kamienia, magnetytu i rdzy. Niepalny, niskopienisty, biodegradowalny. Stosować jako 5% roztwór przy 55–65°C; kontrolować pH. Spłukać po użyciu.',
      de: 'DG CIP Descaler ist ein hochkonzentriertes Gemisch aus Säuren, Enzymen und Tensiden zur Entfernung von Kalk, Magnetit und Rost. Nicht entflammbar, schaumarm, biologisch abbaubar. 5%-Lösung bei 55–65°C.',
    },
    zones: ['cooling', 'engine_room'],
    tags: ['CIP', 'descaler', 'scale', 'heat exchanger', 'ballast', 'enzyme', 'biodegradable'],
    isBiological: true,
    dosage: { baseConc: 50, unit: 'ml/L', notesEn: 'Use 5% solution at 55–65°C; monitor pH; rinse after.' },
    category: 'Biological',
    image: '/products/bio/CIP Descaler 25 L krzywe_zielony.jpg',
  },
  {
    id: '16', slug: 'citrasolv-ex',
    name: { en: 'DG CitraSolv EX', pl: 'DG CitraSolv EX', de: 'DG CitraSolv EX' },
    shortDesc: {
      en: 'Biodegradable industrial degreaser with orange terpenes for grease, oil, tar and adhesives.',
      pl: 'Biodegradowalny odtłuszczacz przemysłowy z terpenami pomarańczowymi do tłuszczów, olejów i klejów.',
      de: 'Biologisch abbaubarer Industrieentfetter mit Orangenterpenen für Fette, Öle und Klebstoffe.',
    },
    description: {
      en: 'DG CitraSolv EX is a highly concentrated water-based biodegradable industrial degreaser containing powerful orange terpenes. Removes grease, oil, tar, inks, waxes, and adhesives from glass, metal, ceramics, and plastics. Dilute 1:20–1:100 for general use; 1:10–1:50 for immersion. Available as 25 L concentrate.',
      pl: 'DG CitraSolv EX to skoncentrowany biodegradowalny odtłuszczacz z terpenami pomarańczowymi. Usuwa smary, oleje, smołę i kleje. Rozcieńczenie 1:20–1:100 ogólne; 1:10–1:50 zanurzenie. Koncentrat 25 L.',
      de: 'DG CitraSolv EX ist ein hochkonzentrierter biologisch abbaubarer Industrieentfetter mit Orangenterpenen. Entfernt Fette, Öle, Teer und Klebstoffe. Verdünnung 1:20–1:100 allgemein; 1:10–1:50 Eintauchen.',
    },
    zones: ['cooling', 'engine_room', 'galley'],
    tags: ['citrus', 'terpene', 'degreaser', 'biodegradable', 'solvent', 'orange'],
    isBiological: false,
    dosage: { baseConc: 50, unit: 'ml/L', notesEn: '1:20–1:100 general cleaning; 1:10–1:50 immersion.' },
    category: 'Engine Room',
    image: '/products/CitraSolv EX 25 L krzywe_niebieska.jpg',
  },
  {
    id: '17', slug: 'coldfuel-conditioner',
    name: { en: 'DG ColdFuel Conditioner', pl: 'DG ColdFuel Conditioner', de: 'DG ColdFuel Conditioner' },
    shortDesc: {
      en: 'Dissolves fuel sludge, inhibits paraffin wax separation and reduces filter clogging.',
      pl: 'Dysperguje szlam paliwowy, hamuje separację parafiny i redukuje zatkania filtrów.',
      de: 'Löst Kraftstoffschlamm, hemmt Paraffinausscheidung und reduziert Filterverstopfungen.',
    },
    description: {
      en: 'DG ColdFuel Conditioner dissolves and disperses sludge in marine diesel fuel, inhibits paraffin wax separation, and reduces filter clogging. Breaks water-oil emulsions and improves purifier efficiency. Contains a corrosion inhibitor. Dose at 1:1000 to 1:2000 directly into the bunker tank before bunkering.',
      pl: 'DG ColdFuel Conditioner dysperguje szlam paliwowy, hamuje separację parafiny i redukuje zatkania filtrów. Rozbija emulsje woda-olej i poprawia wydajność oczyszczarki. Dozować 1:1000 do 1:2000 do zbiornika bunkrowego.',
      de: 'DG ColdFuel Conditioner löst Kraftstoffschlamm, hemmt Paraffinausscheidung und verbessert die Trennleistung. Dosierung 1:1000 bis 1:2000 in den Bunkertank.',
    },
    zones: ['fuel'],
    tags: ['fuel conditioner', 'sludge', 'paraffin', 'cold weather', 'bunker', 'filter'],
    isBiological: false,
    dosage: { baseConc: 0.8, unit: 'ml/L', notesEn: 'Dose 1:1000–1:2000 directly into bunker tank.' },
    category: 'Fuel',
    image: '/products/ColdFuel Conditioner krzywe_biała.jpg',
  },
  {
    id: '18', slug: 'condensate-auto-boiler',
    name: { en: 'DG Condensate Auto Boiler', pl: 'DG Condensate Auto Boiler', de: 'DG Condensate Auto Boiler' },
    shortDesc: {
      en: 'Concentrated boiler water treatment with amines for automatic dosing units.',
      pl: 'Skoncentrowany preparat do kotłów z aminami, przeznaczony do automatycznych jednostek dozujących.',
      de: 'Konzentriertes Kesselspeisewasserbehandlungsmittel mit Aminen für automatische Dosieranlagen.',
    },
    description: {
      en: 'DG Condensate Auto Boiler (DG CAB) is a concentrated boiler water treatment containing amines, anti-foam, scale controlling agent, and potassium hydroxide for corrosion control in steam and condensate systems. Designed for use with automatic dosing units. Initial dose: 2.4 L per ton of boiler capacity.',
      pl: 'DG Condensate Auto Boiler to skoncentrowany preparat do kotłów zawierający aminy i inhibitory dla ochrony przed korozją układów parowych. Przeznaczony do automatycznych jednostek dozujących. Dawka wstępna: 2,4 L/tonę pojemności kotła.',
      de: 'DG Condensate Auto Boiler ist ein konzentriertes Kesselspeisewasserbehandlungsmittel mit Aminen, Anti-Schaum und pH-Regulierung für automatische Dosieranlagen. Startdosis: 2,4 L pro Tonne Kesselinhalt.',
    },
    zones: ['engine_room'],
    tags: ['boiler', 'condensate', 'amine', 'corrosion', 'steam', 'auto dosing'],
    isBiological: false,
    dosage: { baseConc: 2.4, unit: 'ml/L', notesEn: 'Initial: 2.4 L per ton boiler capacity; maintain via auto dosing.' },
    category: 'Engine Room',
    image: '/products/Condesate Auto Boiler krzywe_biała.jpg',
  },
  {
    id: '19', slug: 'condensate-control',
    name: { en: 'DG Condensate Control', pl: 'DG Condensate Control', de: 'DG Condensate Control' },
    shortDesc: {
      en: 'Corrosion control agent with amines for steam and condensate water systems at all pressures.',
      pl: 'Środek korozji z aminami dla parowych układów kondensatowych pod każdym ciśnieniem.',
      de: 'Korrosionsschutzmittel mit Aminen für Dampf- und Kondensatsysteme bei allen Drücken.',
    },
    description: {
      en: 'DG Condensate Control is a concentrated corrosion control agent with amines, anti-foam, and scale controlling agent for steam and condensate water systems at all pressures. Optimal pH range 8.2–9.5. Recommended dosage approximately 50 ml per 24 hours for an average 1 m³ system. Available in 25 L concentrate.',
      pl: 'DG Condensate Control to skoncentrowany środek korozji dla parowych układów kondensatowych. Optymalny zakres pH: 8,2–9,5. Dawkowanie ok. 50 ml na 24 h dla układu 1 m³. Koncentrat 25 L.',
      de: 'DG Condensate Control ist ein konzentriertes Korrosionsschutzmittel mit Aminen für Dampf- und Kondenssysteme. Optimaler pH: 8,2–9,5. Dosierung ca. 50 ml/24 h für 1 m³-Anlagen.',
    },
    zones: ['engine_room'],
    tags: ['boiler', 'condensate', 'corrosion', 'amine', 'pH', 'steam'],
    isBiological: false,
    dosage: { baseConc: 50, unit: 'ml/L', notesEn: 'Approx. 50 ml per 24 h per 1 m³ system; maintain pH 8.2–9.5.' },
    category: 'Engine Room',
    image: '/products/Condesate Control krzywe_biała.jpg',
  },
  {
    id: '20', slug: 'cooltreat-fa',
    name: { en: 'DG Cooltreat FA', pl: 'DG Cooltreat FA', de: 'DG Cooltreat FA' },
    shortDesc: {
      en: 'Nitrite-free corrosion inhibitor for closed cooling systems including aluminium components.',
      pl: 'Bezoazotynowy inhibitor korozji dla zamkniętych układów chłodzenia, w tym elementów aluminiowych.',
      de: 'Nitritfreier Korrosionsinhibitor für geschlossene Kühlsysteme inkl. Aluminiumkomponenten.',
    },
    description: {
      en: 'DG Cooltreat FA is a concentrated liquid corrosion inhibitor for all engine types and closed cooling water systems including aluminium components. Free from nitrites and silicates for long-term stability. Initial dosage: 82 L per ton of distilled water; maintains protection 2–5 years. Compatible with glycols.',
      pl: 'DG Cooltreat FA to skoncentrowany inhibitor korozji dla zamkniętych układów chłodzenia, w tym elementów aluminiowych. Bez azotynów i krzemianów. Dawka wstępna: 82 L/tonę wody; ochrona 2–5 lat. Kompatybilny z glikolami.',
      de: 'DG Cooltreat FA ist ein konzentrierter Korrosionsinhibitor für geschlossene Kühlsysteme inkl. Aluminiumkomponenten. Nitrit- und silikatfrei. Startdosis: 82 L/t Destillat; Schutz 2–5 Jahre.',
    },
    zones: ['cooling'],
    tags: ['coolant', 'corrosion inhibitor', 'aluminium', 'closed cooling', 'nitrite-free', 'glycol'],
    isBiological: false,
    dosage: { baseConc: 82, unit: 'ml/L', notesEn: 'Initial: 82 L/t distilled water. Maintain concentration via test kit.' },
    category: 'Cooling',
    image: '/products/Cooltreat FA krzywe_biała.jpg',
  },
  {
    id: '21', slug: 'deck-cleaner-marine',
    name: { en: 'DG Deck Cleaner Marine', pl: 'DG Deck Cleaner Marine', de: 'DG Deck Cleaner Marine' },
    shortDesc: {
      en: 'Slightly alkaline multi-purpose cleaner for deck and engine room, removing oils and carbon deposits.',
      pl: 'Lekko zasadowy środek wielofunkcyjny do pokładów i maszynowni, usuwający oleje i osady.',
      de: 'Leicht alkalischer Mehrzweckreiniger für Decks und Maschinenräume, entfernt Öle und Ablagerungen.',
    },
    description: {
      en: 'DG Deck Cleaner Marine is a slightly alkaline water-based multi-purpose cleaner for deck and engine room surfaces. Removes greasy grime, oil, diesel spillages, sludge, wax, and carbon deposits. Apply undiluted or diluted up to 1:50; compatible with steam cleaning (1:10–1:50). Available as 25 L concentrate.',
      pl: 'DG Deck Cleaner Marine to lekko zasadowy środek czyszczący do pokładów i maszynowni. Usuwa oleje, rozlane paliwo, szlam i osady węglowe. Rozcieńczenie do 1:50; kompatybilny z czyszczeniem parowym. Koncentrat 25 L.',
      de: 'DG Deck Cleaner Marine ist ein leicht alkalischer Mehrzweckreiniger für Decks und Maschinenräume. Entfernt Öle, Kraftstoffverschüttungen und Kohlenstoffablagerungen. Verdünnung bis 1:50.',
    },
    zones: ['deck', 'engine_room'],
    tags: ['deck', 'cleaner', 'degreaser', 'marine', 'oil', 'carbon', 'alkaline'],
    isBiological: false,
    dosage: { baseConc: 20, unit: 'ml/L', notesEn: 'Undiluted heavy duty; dilute to 1:50 general; 1:10–1:50 steam.' },
    category: 'Deck',
    image: '/products/Deck Cleaner Marine krzywe_niebieska.jpg',
  },
  {
    id: '22', slug: 'defoam-c',
    name: { en: 'DG Defoam C', pl: 'DG Defoam C', de: 'DG Defoam C' },
    shortDesc: {
      en: 'Highly concentrated non-toxic defoamer for water tanks, sewage treatment and industrial wastewater.',
      pl: 'Wysoce skoncentrowany niepalny środek odpieniający do zbiorników wodnych i oczyszczalni ścieków.',
      de: 'Hochkonzentriertes nicht toxisches Entschäumungsmittel für Wassertanks und Abwasserbehandlung.',
    },
    description: {
      en: 'DG Defoam C is a highly concentrated liquid defoamer with fast foam suppression and minimal dosage requirements. Non-corrosive, non-toxic, non-flammable. Suitable for water tanks, sewage treatment, and industrial wastewater under alkaline conditions. Dosage 50–500 ml per ton; apply by drops or spray. Available in 25 L concentrate.',
      pl: 'DG Defoam C to wysoce skoncentrowany środek odpieniający o szybkim działaniu. Niekorozyjny, niepalny. Do zbiorników wodnych i oczyszczalni ścieków. Dawka 50–500 ml/tonę. Koncentrat 25 L.',
      de: 'DG Defoam C ist ein hochkonzentriertes Entschäumungsmittel mit schneller Wirkung. Nicht korrosiv, nicht brennbar. Für Wassertanks und Abwasserbehandlung. Dosierung 50–500 ml/t.',
    },
    zones: ['engine_room', 'accommodation'],
    tags: ['defoamer', 'foam control', 'sewage', 'water treatment', 'alkaline', 'non-toxic'],
    isBiological: false,
    dosage: { baseConc: 0.3, unit: 'ml/L', notesEn: 'Dose 50–500 ml per ton depending on foam level.' },
    category: 'Engine Room',
    image: '/products/Defoam krzywe_biała.jpg',
  },
  {
    id: '23', slug: 'degreaser-hd',
    name: { en: 'DG Degreaser HD', pl: 'DG Degreaser HD', de: 'DG Degreaser HD' },
    shortDesc: {
      en: 'Concentrated biodegradable heavy-duty degreaser with orange terpenes for all surfaces.',
      pl: 'Skoncentrowany biodegradowalny odtłuszczacz heavy-duty z terpenami pomarańczowymi.',
      de: 'Konzentrierter biologisch abbaubarer Schwerlastentfetter mit Orangenterpenen.',
    },
    description: {
      en: 'DG Degreaser HD is a highly concentrated water-based biodegradable heavy-duty degreaser with orange terpenes. Removes grease, oil, tar, inks, waxes, and adhesives from glass, metal, ceramics, and plastics. Dilute 1:1 to 1:20 for general cleaning; 1:5–1:20 for immersion. Contact time: 5 min to 2 h.',
      pl: 'DG Degreaser HD to skoncentrowany biodegradowalny odtłuszczacz z terpenami pomarańczowymi. Usuwa tłuszcze, oleje, smołę i kleje. Rozcieńczenie 1:1 do 1:20 ogólne; 1:5–1:20 zanurzenie. Czas kontaktu: 5 min–2 h.',
      de: 'DG Degreaser HD ist ein hochkonzentrierter biologisch abbaubarer Schwerlastentfetter mit Orangenterpenen. Entfernt Fette, Öle und Klebstoffe. Kontaktzeit: 5 Min. bis 2 Std.',
    },
    zones: ['engine_room', 'deck'],
    tags: ['degreaser', 'heavy duty', 'terpene', 'biodegradable', 'orange', 'grease'],
    isBiological: false,
    dosage: { baseConc: 50, unit: 'ml/L', notesEn: '1:1–1:20 general; 1:5–1:20 immersion; contact 5 min–2 h.' },
    category: 'Engine Room',
    image: '/products/Deagreser HD krzywe_niebieska.jpg',
  },
  {
    id: '24', slug: 'descaler-ca-bioactivae',
    name: { en: 'DG Descaler CA BioActivae', pl: 'DG Descaler CA BioActivae', de: 'DG Descaler CA BioActivae' },
    shortDesc: {
      en: 'Concentrated mixed acids and enzymes for safe removal of scale, magnetite and rust from water systems.',
      pl: 'Skoncentrowana mieszanina kwasów i enzymów do bezpiecznego usuwania kamienia i rdzy.',
      de: 'Konzentriertes Gemisch aus Säuren und Enzymen zur sicheren Entkalkung und Rostentfernung.',
    },
    description: {
      en: 'DG Descaler CA BioActivae is a highly concentrated liquid of mixed acids and enzymes for safe removal of scale, magnetite, algae, lime, and rust from water systems. Non-corrosive, non-flammable, biodegradable. Use 10–20% in circulating systems or 10–50% in immersion at 55–65°C. Available as 25 L concentrate.',
      pl: 'DG Descaler CA BioActivae to skoncentrowana mieszanina kwasów i enzymów do usuwania kamienia i rdzy. Niekorozyjny, biodegradowalny. Stosować 10–20% w obiegach lub 10–50% w kąpieli w 55–65°C. Koncentrat 25 L.',
      de: 'DG Descaler CA BioActivae ist ein hochkonzentriertes Gemisch aus Säuren und Enzymen zur Entkalkung. Nicht korrosiv, biologisch abbaubar. 10–20% in Umlaufsystemen oder 10–50% als Tauchbad bei 55–65°C.',
    },
    zones: ['cooling', 'engine_room'],
    tags: ['descaler', 'enzyme', 'scale', 'heat exchanger', 'biodegradable', 'magnetite'],
    isBiological: false,
    dosage: { baseConc: 15, unit: '%', notesEn: '10–20% circulating systems; 10–50% immersion at 55–65°C.' },
    category: 'Engine Room',
    image: '/products/Descaler CA krzywe_czarna.jpg',
  },
  {
    id: '25', slug: 'descaler-l',
    name: { en: 'DG Descaler L', pl: 'DG Descaler L', de: 'DG Descaler L' },
    shortDesc: {
      en: 'Concentrated acidic descaling agent based on mixed strong acids for limestone, scale and rust.',
      pl: 'Skoncentrowany kwaśny środek odkamieniający na bazie mocnych kwasów do wapienia, kamienia i rdzy.',
      de: 'Konzentriertes saures Entkalkungsmittel auf Basis starker Säuren für Kalk, Stein und Rost.',
    },
    description: {
      en: 'DG Descaler L is a highly concentrated acidic descaling agent based on mixed strong acids for removing limestone, scale, rust, concrete, and cement. Contains corrosion inhibitors and anti-foam. Use as 15–30% solution in circulating systems or 10–50% in immersion baths (max 55°C). For acid-resistant surfaces only.',
      pl: 'DG Descaler L to skoncentrowany kwaśny środek odkamieniający na bazie mocnych kwasów. Do usuwania wapienia, kamienia i rdzy. Stosować 15–30% w obiegach lub 10–50% w kąpieli (maks. 55°C). Tylko na powierzchniach kwasoodpornych.',
      de: 'DG Descaler L ist ein hochkonzentriertes saures Entkalkungsmittel auf Basis starker Säuren. Entfernt Kalk, Rost und Beton. 15–30% in Umlaufsystemen oder 10–50% als Tauchbad (max. 55°C).',
    },
    zones: ['cooling', 'engine_room'],
    tags: ['descaler', 'acid', 'limescale', 'boiler', 'heat exchanger', 'strong acid'],
    isBiological: false,
    dosage: { baseConc: 20, unit: '%', notesEn: '15–30% circulating; 10–50% immersion bath (max 55°C).' },
    category: 'Engine Room',
    image: '/products/Descaler L krzywe_czarna.jpg',
  },
  {
    id: '26', slug: 'diesel-lubricity-agent',
    name: { en: 'DG Diesel Lubricity Agent', pl: 'DG Diesel Lubricity Agent', de: 'DG Diesel Lubricity Agent' },
    shortDesc: {
      en: 'Improves lubricity of Ultra Low Sulphur Distillate marine fuels, reducing fuel pump wear.',
      pl: 'Poprawia smarność morskich paliw ULSD, redukując zużycie pomp paliwowych.',
      de: 'Verbessert die Schmierfähigkeit von ULSD-Kraftstoffen, reduziert Verschleiß in Kraftstoffpumpen.',
    },
    description: {
      en: 'DG Diesel Lubricity Agent improves lubricity of Ultra Low Sulphur Distillate marine fuels, reducing wear in fuel pumps. Fully compatible with other diesel detergent packages. Dose 1 L per 10,000–40,000 L of fuel; add directly to tank before bunkering. Shelf life 24 months. Available as 25 L concentrate.',
      pl: 'DG Diesel Lubricity Agent poprawia smarność morskich paliw ULSD, redukując zużycie pomp. Dawkowanie 1 L na 10 000–40 000 L paliwa; dodawać do zbiornika przed bunkrowaniem. Trwałość 24 miesiące.',
      de: 'DG Diesel Lubricity Agent verbessert die Schmierfähigkeit von ULSD-Kraftstoffen, reduziert Verschleiß in Kraftstoffpumpen. 1 L pro 10.000–40.000 L Kraftstoff; vor dem Bunkern hinzufügen.',
    },
    zones: ['fuel'],
    tags: ['lubricity', 'ULSD', 'fuel additive', 'diesel', 'wear protection', 'pump'],
    isBiological: false,
    dosage: { baseConc: 0.1, unit: 'ml/L', notesEn: '1 L per 10,000–40,000 L fuel; add before bunkering.' },
    category: 'Fuel',
    image: '/products/Diesel Lubricity Agent krzywe_czerwona.jpg',
  },
  {
    id: '27', slug: 'diesel-prt',
    name: { en: 'DG Diesel PRT', pl: 'DG Diesel PRT', de: 'DG Diesel PRT' },
    shortDesc: {
      en: 'Biodegradable corrosion and scale inhibitor for closed heating and cooling water systems.',
      pl: 'Biodegradowalny inhibitor korozji i kamienia dla zamkniętych układów grzewczych i chłodniczych.',
      de: 'Biologisch abbaubarer Korrosions- und Kalkschutzinhibitor für geschlossene Heiz- und Kühlsysteme.',
    },
    description: {
      en: 'DG Diesel PRT is a safe water-based biodegradable corrosion and scale inhibitor for closed heating and cooling water systems. Compatible with glycol for frost protection. Starting dosage: 8 L per m³ of distilled water to achieve minimum 1000 ppm nitrite. Maintain nitrite level 1000–2000 ppm. Available as 25 L concentrate.',
      pl: 'DG Diesel PRT to biodegradowalny inhibitor korozji i kamienia dla zamkniętych układów grzewczych i chłodniczych. Kompatybilny z glikolem. Dawka startowa: 8 L/m³; utrzymywać azotynu 1000–2000 ppm.',
      de: 'DG Diesel PRT ist ein sicherer wasserbasierter Korrosions- und Kalkschutzinhibitor für geschlossene Heiz- und Kühlsysteme. Startdosis: 8 L/m³; Nitritspiegel 1000–2000 ppm halten.',
    },
    zones: ['fuel', 'engine_room'],
    tags: ['corrosion inhibitor', 'cooling water', 'nitrite', 'scale', 'closed system', 'glycol'],
    isBiological: false,
    dosage: { baseConc: 8, unit: 'ml/L', notesEn: 'Start: 8 L per m³ distilled water; maintain nitrite 1000–2000 ppm.' },
    category: 'Fuel',
    image: '/products/Diesel PRT krzywe_biała.jpg',
  },
  {
    id: '28', slug: 'elektrocleaner-fast-fry',
    name: { en: 'DG Elektrocleaner Fast Dry', pl: 'DG Elektrocleaner Fast Dry', de: 'DG Elektrocleaner Fast Dry' },
    shortDesc: {
      en: 'Fast-drying non-conductive solvent cleaner for electrical machines and components.',
      pl: 'Szybkoschnący nieprzewodzący rozpuszczalnik do maszyn i podzespołów elektrycznych.',
      de: 'Schnelltrocknender nicht-leitender Lösemittelreiniger für Elektromotoren und -komponenten.',
    },
    description: {
      en: 'DG Elektrocleaner Fast Dry is a fast-drying non-conductive solvent cleaner for electrical machines and components. Free from chlorinated solvents and virtually odourless. Penetrates rapidly and leaves no moisture residue. Apply by brush, swab, spray, or immersion; residual solvent evaporates quickly.',
      pl: 'DG Elektrocleaner Fast Dry to szybkoschnący nieprzewodzący rozpuszczalnik do maszyn elektrycznych. Bez chlorowanych rozpuszczalników, praktycznie bezwonny. Stosować pędzlem, wacikiem, natryskiem lub zanurzeniem; pozostałości odparowują samoistnie.',
      de: 'DG Elektrocleaner Fast Dry ist ein schnelltrocknender nicht-leitender Lösemittelreiniger für Elektromotoren. Chlorlösemittelfrei, geruchsarm. Rückstände verdampfen schnell.',
    },
    zones: ['engine_room'],
    tags: ['electrical', 'solvent cleaner', 'fast dry', 'motor', 'non-conductive', 'chlorine-free'],
    isBiological: false,
    dosage: { baseConc: 100, unit: 'ml/L', notesEn: 'Apply undiluted; allow to evaporate — no rinsing needed.' },
    category: 'Engine Room',
    image: '/products/Elekrocleaner fast dry krzywe_żółta.jpg',
  },
  {
    id: '29', slug: 'elektrocleaner',
    name: { en: 'DG Elektrocleaner', pl: 'DG Elektrocleaner', de: 'DG Elektrocleaner' },
    shortDesc: {
      en: 'Non-conductive solvent cleaner with high flash point for electrical machinery and equipment.',
      pl: 'Nieprzewodzący rozpuszczalnik o wysokiej temperaturze zapłonu do maszyn elektrycznych.',
      de: 'Nicht-leitender Lösemittelreiniger mit hohem Flammpunkt für Elektromaschinen.',
    },
    description: {
      en: 'DG Elektrocleaner is a non-conductive solvent cleaner for oil and grease removal from electrical machinery and equipment. No chlorinated solvents, virtually odourless, high flash point for enhanced safety. Quick-acting, penetrates effectively, and leaves no residue. Suitable for brush, swab, spray, or immersion.',
      pl: 'DG Elektrocleaner to nieprzewodzący rozpuszczalnik do maszyn elektrycznych. Bez chlorowanych rozpuszczalników, wysoka temperatura zapłonu. Szybkie działanie, bez pozostałości. Stosować pędzlem, wacikiem, natryskiem lub zanurzeniem.',
      de: 'DG Elektrocleaner ist ein nicht-leitender Lösemittelreiniger für Elektromaschinen. Chlorlösemittelfrei, hoher Flammpunkt für mehr Sicherheit. Schnell wirkend, hinterlässt keine Rückstände.',
    },
    zones: ['engine_room'],
    tags: ['electrical', 'solvent cleaner', 'motor', 'non-conductive', 'degreaser', 'high flash'],
    isBiological: false,
    dosage: { baseConc: 100, unit: 'ml/L', notesEn: 'Apply undiluted by brush, swab, or spray.' },
    category: 'Engine Room',
    image: '/products/Elekrocleaner krzywe_żółta.jpg',
  },
  {
    id: '30', slug: 'engine-cleaner',
    name: { en: 'DG Engine Cleaner', pl: 'DG Engine Cleaner', de: 'DG Engine Cleaner' },
    shortDesc: {
      en: 'Heavy-duty water-based micro-emulsion cleaner and degreaser for engine room maintenance.',
      pl: 'Przemysłowy środek czyszczący w postaci mikroemulsji do konserwacji siłowni okrętowych.',
      de: 'Schwerlastiger wasserbasierter Mikro-Emulsionsreiniger für die Maschinenraumwartung.',
    },
    description: {
      en: 'DG Engine Cleaner is a heavy-duty water-based micro-emulsion cleaner and degreaser for engine room maintenance. Effectively removes grease, carbon deposits, grime, oil, and dirt from all surface types. Non-flammable; apply by brush, hand spray, or immersion at dilution ratios up to 1:5.',
      pl: 'DG Engine Cleaner to przemysłowy wodny środek czyszczący w postaci mikroemulsji do siłowni okrętowych. Usuwa smary, osady węglowe, oleje i zanieczyszczenia. Niepalny; rozcieńczenie do 1:5.',
      de: 'DG Engine Cleaner ist ein schwerlastiger wasserbasierter Mikro-Emulsionsreiniger für Maschinenräume. Entfernt Fette, Kohlenstoff und Öle. Nicht brennbar; Verdünnung bis 1:5.',
    },
    zones: ['engine_room'],
    tags: ['engine room', 'degreaser', 'micro-emulsion', 'carbon', 'heavy duty', 'machinery'],
    isBiological: false,
    dosage: { baseConc: 200, unit: 'ml/L', notesEn: 'Dilute up to 1:5; apply by brush, spray, or immersion.' },
    category: 'Engine Room',
    image: '/products/Engine Cleaner krzywe_niebieska.jpg',
  },
  {
    id: '31', slug: 'envirocleaner',
    name: { en: 'DG Envirocleaner', pl: 'DG Envirocleaner', de: 'DG Envirocleaner' },
    shortDesc: {
      en: 'Safe multi-purpose degreaser on natural orange extracts for decks and machinery surfaces.',
      pl: 'Bezpieczny wielofunkcyjny odtłuszczacz na naturalnych ekstraktach pomarańczowych do pokładów i maszyn.',
      de: 'Sicherer Mehrzweckentfetter auf Basis natürlicher Orangenextrakte für Decks und Maschinen.',
    },
    description: {
      en: 'DG Envirocleaner is a safe water-based multi-purpose degreaser formulated on natural orange solvent extracts and advanced surfactants. Cleans and degreases decks, machinery, and surfaces — removing oil, diesel spillages, sludge, and carbon deposits. Use undiluted for heavy soiling or diluted up to 1:50.',
      pl: 'DG Envirocleaner to bezpieczny odtłuszczacz wielofunkcyjny na bazie naturalnych ekstraktów pomarańczowych. Usuwa oleje, rozlane paliwo, szlam i osady węglowe. Rozcieńczenie do 1:50 przy lekkich zabrudzeniach.',
      de: 'DG Envirocleaner ist ein sicherer Mehrzweckentfetter auf Basis natürlicher Orangenextrakte. Reinigt Decks und Maschinen, entfernt Öle und Kraftstoffrückstände. Unverdünnt oder bis 1:50 verdünnt.',
    },
    zones: ['deck', 'accommodation'],
    tags: ['eco', 'orange', 'natural', 'degreaser', 'deck', 'biodegradable', 'solvent'],
    isBiological: false,
    dosage: { baseConc: 20, unit: 'ml/L', notesEn: 'Undiluted heavy duty; dilute up to 1:50 general cleaning.' },
    category: 'Deck',
    image: '/products/Envirocleaner krzywe_niebieska.jpg',
  },
  {
    id: '32', slug: 'fastmax',
    name: { en: 'DG FastMAX', pl: 'DG FastMAX', de: 'DG FastMAX' },
    shortDesc: {
      en: 'Powerful alkaline cleaner for heavy-duty use in engine rooms, decks and cargo spaces.',
      pl: 'Wydajny alkaliczny środek do intensywnego czyszczenia siłowni, pokładów i przestrzeni ładunkowych.',
      de: 'Leistungsstarker alkalischer Reiniger für Schwerlastanwendungen in Maschinenräumen und Laderäumen.',
    },
    description: {
      en: 'DG FastMAX is a powerful water-based alkaline cleaner and degreaser for heavy-duty use in engine rooms, decks, and cargo spaces. Removes grease, oil, carbon deposits, sludge, and diesel spillages. Apply by foam nozzle, brush, cloth, or immersion at dilution ratios 1:10 to 1:100 for general cleaning.',
      pl: 'DG FastMAX to wydajny alkaliczny środek czyszczący do siłowni, pokładów i przestrzeni ładunkowych. Usuwa tłuszcze, oleje, szlam. Rozcieńczenie 1:10 do 1:100 ogólne, 1:25 zanurzenie.',
      de: 'DG FastMAX ist ein leistungsstarker wasserbasierter alkalischer Reiniger für Schwerlastanwendungen in Maschinenräumen, Decks und Laderäumen. Verdünnung 1:10 bis 1:100.',
    },
    zones: ['engine_room', 'deck'],
    tags: ['alkaline', 'degreaser', 'fast', 'heavy duty', 'foam', 'cargo'],
    isBiological: false,
    dosage: { baseConc: 50, unit: 'ml/L', notesEn: 'General 1:10–1:100; immersion 1:25; foam equipment neat.' },
    category: 'Engine Room',
    image: '/products/Fast Max krzywe_niebieska.jpg',
  },
  {
    id: '33', slug: 'filtercleaner',
    name: { en: 'DG Filtercleaner', pl: 'DG Filtercleaner', de: 'DG Filtercleaner' },
    shortDesc: {
      en: 'Specialist heavy-duty cleaner for fuel filters, oil coolers and separator bowls.',
      pl: 'Specjalistyczny środek heavy-duty do filtrów paliwowych, chłodnic oleju i mis separatorów.',
      de: 'Spezieller Schwerlastenreiniger für Kraftstofffilter, Ölkühler und Separatorschüsseln.',
    },
    description: {
      en: 'DG Filtercleaner is a specialist heavy-duty cleaner for fuel filters, pre-heaters, oil coolers, burner tips, and metal or ceramic oil filters. After cleaning, separates into oil and water phases for easy disposal. Free from chlorinated solvents. Use undiluted at max 70°C; contact time 2–8 hours.',
      pl: 'DG Filtercleaner to specjalistyczny środek do filtrów paliwowych, chłodnic oleju i dysz palnikowych. Po czyszczeniu rozdziela się na fazę olejową i wodną. Bez chlorowanych rozpuszczalników. Stosować nierozcieńczony w maks. 70°C przez 2–8 h.',
      de: 'DG Filtercleaner ist ein Spezialreiniger für Kraftstofffilter, Ölkühler und Brennerdüsen. Trennt sich nach der Reinigung in Öl- und Wasserphase. Chlorlösemittelfrei. Unverdünnt bei max. 70°C.',
    },
    zones: ['engine_room', 'fuel'],
    tags: ['filter', 'fuel filter', 'oil cooler', 'burner', 'specialist', 'separator'],
    isBiological: false,
    dosage: { baseConc: 100, unit: 'ml/L', notesEn: 'Use undiluted at max 70°C; contact time 2–8 hours.' },
    category: 'Engine Room',
    image: '/products/Fitercleaner krzywe_niebieska.jpg',
  },
  {
    id: '34', slug: 'high-pressure-cleaner',
    name: { en: 'DG High Pressure Cleaner', pl: 'DG High Pressure Cleaner', de: 'DG High Pressure Cleaner' },
    shortDesc: {
      en: 'Alkaline biodegradable high-foam cleaning agent for high-pressure washers and foam equipment.',
      pl: 'Alkaliczny biodegradowalny środek wysokopienisty do myjek wysokociśnieniowych i urządzeń pianowych.',
      de: 'Alkalischer biologisch abbaubarer Hochschaum-Reiniger für Hochdruckreiniger und Schaumgeräte.',
    },
    description: {
      en: 'DG High Pressure Cleaner is a powerful alkaline water-soluble biodegradable cleaning agent with high-foam effect. Combines surfactants, sequestering agents, inhibitors, and alkali in high concentration. Removes oils, fats, greases, soot, and cargo residues. Use with high-pressure washers (10–25%) or foam equipment (1–2%).',
      pl: 'DG High Pressure Cleaner to alkaliczny biodegradowalny środek wysokopienisty. Usuwa oleje, tłuszcze, sadzę i pozostałości ładunku. Do myjek wysokociśnieniowych (10–25%) lub urządzeń pianowych (1–2%).',
      de: 'DG High Pressure Cleaner ist ein alkalischer, biologisch abbaubarer Reiniger mit hohem Schaum. Für Hochdruckreiniger (10–25%) oder Schaumgeräte (1–2%). Entfernt Öle, Fette und Fracht.',
    },
    zones: ['deck', 'engine_room'],
    tags: ['high pressure', 'foam', 'alkaline', 'biodegradable', 'cargo', 'soot'],
    isBiological: false,
    dosage: { baseConc: 15, unit: '%', notesEn: '10–25% for high-pressure washers; 1–2% for foam equipment.' },
    category: 'Deck',
    image: '/products/HP Wash krzywe_niebieska.jpg',
  },
  {
    id: '35', slug: 'multicleaner-eco',
    name: { en: 'DG Multicleaner ECO', pl: 'DG Multicleaner ECO', de: 'DG Multicleaner ECO' },
    shortDesc: {
      en: 'Biodegradable universal cleaner with water softeners and fresh lemon scent.',
      pl: 'Biodegradowalny uniwersalny środek czyszczący ze zmiękczaczami wody i świeżym zapachem cytryny.',
      de: 'Biologisch abbaubarer Universalreiniger mit Wasserenthärtern und frischem Zitronenduft.',
    },
    description: {
      en: 'DG Multicleaner ECO is a safe water-soluble biodegradable universal cleaner and degreaser with water softeners. Removes grease, oils, tar, inks, wax, and adhesives from glass, metal, ceramics, and plastics — leaving a fresh lemon scent. Dilute 1:1–1:10 general, 1:10–1:50 steam cleaning.',
      pl: 'DG Multicleaner ECO to biodegradowalny uniwersalny środek czyszczący ze zmiękczaczami wody. Usuwa tłuszcze, oleje, smołę i kleje ze szkła, metalu i ceramiki. Świeży zapach cytryny. Rozcieńczenie 1:1–1:10 ogólne.',
      de: 'DG Multicleaner ECO ist ein biologisch abbaubarer Universalreiniger mit Wasserenthärtern. Entfernt Öle, Teer und Klebstoffe. Frischer Zitronenduft. Verdünnung 1:1–1:10 allgemein.',
    },
    zones: ['deck', 'accommodation'],
    tags: ['eco', 'biodegradable', 'lemon', 'universal', 'degreaser', 'water softener'],
    isBiological: false,
    dosage: { baseConc: 10, unit: 'ml/L', notesEn: '1:1–1:10 general; 1:10–1:50 steam cleaning.' },
    category: 'Deck',
    image: '/products/Multicleaner ECO krzywe_niebieska.jpg',
  },
  {
    id: '36', slug: 'multicleaner-forte',
    name: { en: 'DG Multicleaner Forte', pl: 'DG Multicleaner Forte', de: 'DG Multicleaner Forte' },
    shortDesc: {
      en: 'Universal alkaline high-foam biodegradable cleaner with powerful water-softening properties.',
      pl: 'Alkaliczny wysokopienisty biodegradowalny środek z silnymi właściwościami zmiękczającymi wodę.',
      de: 'Universeller alkalischer Hochschaum-Reiniger mit starken Wasserenthärtungseigenschaften.',
    },
    description: {
      en: 'DG Multicleaner Forte is a universal alkaline high-foam biodegradable cleaner with powerful water-softening properties. Removes grease, oils, tar, inks, wax, and adhesives from glass, metal, ceramics, and plastics. Fresh lemon scent. Dilute 1:5 to 1:50 general, 1:5–1:20 immersion. For alkali-resistant surfaces.',
      pl: 'DG Multicleaner Forte to alkaliczny wysokopienisty biodegradowalny środek ze zmiękczaczami wody. Usuwa tłuszcze, oleje, smołę i kleje. Świeży zapach cytryny. Rozcieńczenie 1:5 do 1:50.',
      de: 'DG Multicleaner Forte ist ein universeller alkalischer Hochschaum-Reiniger mit Wasserenthärtungseigenschaften. Frischer Zitronenduft. Verdünnung 1:5 bis 1:50.',
    },
    zones: ['deck', 'engine_room'],
    tags: ['alkaline', 'high foam', 'lemon', 'universal', 'biodegradable', 'water softener'],
    isBiological: false,
    dosage: { baseConc: 20, unit: 'ml/L', notesEn: '1:5–1:50 general; 1:5–1:20 immersion.' },
    category: 'Deck',
    image: '/products/Multicleaner Forte krzywe_niebieska.jpg',
  },
  {
    id: '37', slug: 'oil-dispersant',
    name: { en: 'DG Oil Dispersant', pl: 'DG Oil Dispersant', de: 'DG Oil Dispersant' },
    shortDesc: {
      en: 'Concentrated biodegradable formulation for dispersing accidental oil spills on deck and at sea.',
      pl: 'Skoncentrowana biodegradowalna mieszanina do rozpraszania rozlewów olejowych na pokładzie i morzu.',
      de: 'Konzentriertes biologisch abbaubares Mittel zur Dispersion von Ölverschüttungen.',
    },
    description: {
      en: 'DG Oil Dispersant is a concentrated water-based biodegradable formulation for dispersing accidental oil spills on deck and at sea. Disperses mineral oils, crude oil, fuel oil, and lubricant oil. Can also be used as a tank cleaner at 5–10% dilution. Apply undiluted on spills; rinse with high-pressure unit.',
      pl: 'DG Oil Dispersant to skoncentrowana biodegradowalna mieszanina do rozpraszania rozlewów olejowych na pokładzie i na morzu. Działa na oleje mineralne, ropę i oleje smarowe. Stosować nierozcieńczony na plamie, spłukać wysokociśnieniowo.',
      de: 'DG Oil Dispersant ist ein konzentriertes biologisch abbaubares Mittel zur Dispersion von Ölverschüttungen auf Deck und auf See. Wirkt auf Mineralöle, Rohöl und Schmieröle.',
    },
    zones: ['bilge', 'deck'],
    tags: ['oil spill', 'dispersant', 'pollution', 'deck', 'environmental', 'biodegradable'],
    isBiological: false,
    dosage: { baseConc: 100, unit: 'ml/L', notesEn: 'Apply undiluted on spills; 5–10% as tank cleaner.' },
    category: 'Bilge',
    image: '/products/Oil dispersant krzywe_niebieska.jpg',
  },
  {
    id: '38', slug: 'paint-remover',
    name: { en: 'DG Paint Remover', pl: 'DG Paint Remover', de: 'DG Paint Remover' },
    shortDesc: {
      en: 'Removes paints, varnishes and oils from metals and plastics without mechanical scraping.',
      pl: 'Usuwa farby, lakiery i oleje z metali i tworzyw sztucznych bez mechanicznego skrobania.',
      de: 'Entfernt Farben, Lacke und Öle von Metallen und Kunststoffen ohne Kratzen.',
    },
    description: {
      en: 'DG Paint Remover removes paints, varnishes, and oils from iron, aluminium, zinc, nickel, and plastics. Penetrates between coating and surface for removal without scraping. Most effective at 55–65°C. Use undiluted or diluted 1:1 with hot water. Immerse 30 minutes to 4–5 hours; rinse and dry.',
      pl: 'DG Paint Remover usuwa farby, lakiery i oleje z metali i tworzyw sztucznych bez mechanicznego skrobania. Najskuteczniejszy w 55–65°C. Zanurzać 30 min–4–5 h, spłukać i osuszyć.',
      de: 'DG Paint Remover entfernt Farben, Lacke und Öle von Eisen, Aluminium, Zink und Kunststoff ohne Kratzen. Wirksamste Temperatur: 55–65°C. Eintauchdauer 30 Min. bis 5 Std.',
    },
    zones: ['deck'],
    tags: ['paint remover', 'varnish', 'coating', 'aluminium', 'metal', 'stripping'],
    isBiological: false,
    dosage: { baseConc: 100, unit: 'ml/L', notesEn: 'Undiluted or 1:1 at 55–65°C; immerse 30 min–5 h.' },
    category: 'Deck',
    image: '/products/Paint Remover krzywe_czerwona.jpg',
  },
  {
    id: '39', slug: 'petrosolv',
    name: { en: 'DG Petrosolv', pl: 'DG Petrosolv', de: 'DG Petrosolv' },
    shortDesc: {
      en: 'Heavy-duty degreaser of natural solvents for marine surfaces, biodegradable and orange-scented.',
      pl: 'Silnie działający odtłuszczacz z naturalnych rozpuszczalników do powierzchni morskich, biodegradowalny.',
      de: 'Schwerlastentfetter aus natürlichen Lösemitteln für marine Oberflächen, biologisch abbaubar.',
    },
    description: {
      en: 'DG Petrosolv is a heavy-duty degreaser of natural solvents and non-ionic surfactants for marine surfaces. Highly biodegradable and safe on metals and painted surfaces. Apply by brush, spray, immersion, or soaking; rinse after 15–45 minutes contact time with hot high-pressure water. Orange-scented.',
      pl: 'DG Petrosolv to silnie działający odtłuszczacz z naturalnych rozpuszczalników do powierzchni morskich. Wysoce biodegradowalny i bezpieczny dla metali. Spłukać po 15–45 min. Przyjemny zapach pomarańczowy.',
      de: 'DG Petrosolv ist ein Schwerlastentfetter aus natürlichen Lösemitteln für marine Oberflächen. Biologisch abbaubar, sicher auf Metallen. Kontaktzeit 15–45 Min., dann mit Heißwasser abspülen.',
    },
    zones: ['fuel', 'engine_room'],
    tags: ['natural solvent', 'biodegradable', 'degreaser', 'orange', 'marine', 'petroleum'],
    isBiological: false,
    dosage: { baseConc: 100, unit: 'ml/L', notesEn: 'Apply undiluted; contact 15–45 min; rinse with hot water.' },
    category: 'Fuel',
    image: '/products/Petrosolv krzywe_biała.jpg',
  },
  {
    id: '40', slug: 'pipe-cleaner',
    name: { en: 'DG Pipe Cleaner', pl: 'DG Pipe Cleaner', de: 'DG Pipe Cleaner' },
    shortDesc: {
      en: 'Concentrated acidic descaling agent for boilers, condensers, heat exchangers and pipe systems.',
      pl: 'Skoncentrowany kwaśny środek odkamieniający do kotłów, skraplaczy, wymienników i rurociągów.',
      de: 'Konzentriertes saures Entkalkungsmittel für Kessel, Kondensatoren, Wärmetauscher und Rohrsysteme.',
    },
    description: {
      en: 'DG Pipe Cleaner is a highly concentrated acidic descaling agent based on mixed strong acids for removing limestone, scale, rust, concrete, and cement from boilers, condensers, evaporators, heat exchangers, and pipe systems. Use as 10–30% solution in circulating systems (max 55°C). Acid-resistant surfaces only.',
      pl: 'DG Pipe Cleaner to skoncentrowany kwaśny środek odkamieniający do kotłów, skraplaczy i rurociągów. Stosować jako 10–30% w obiegach lub 10–50% w kąpieli (maks. 55°C). Wyłącznie na kwasoodpornych powierzchniach.',
      de: 'DG Pipe Cleaner ist ein hochkonzentriertes saures Entkalkungsmittel für Kessel, Kondensatoren und Rohrsysteme. 10–30% in Umlaufsystemen oder 10–50% als Tauchbad (max. 55°C).',
    },
    zones: ['engine_room', 'cooling'],
    tags: ['pipe', 'descaler', 'acid', 'boiler', 'heat exchanger', 'condenser'],
    isBiological: false,
    dosage: { baseConc: 20, unit: '%', notesEn: '10–30% circulating systems; 10–50% immersion (max 55°C).' },
    category: 'Engine Room',
    image: '/products/Pipe Cleaner krzywe_czarna.jpg',
  },
  {
    id: '41', slug: 'rust-remover',
    name: { en: 'DG Rust Remover', pl: 'DG Rust Remover', de: 'DG Rust Remover' },
    shortDesc: {
      en: 'Phosphoric acid-based liquid for removing rust from steel, cast iron, aluminium and copper.',
      pl: 'Preparat na bazie kwasu fosforowego do usuwania rdzy ze stali, żeliwa, aluminium i miedzi.',
      de: 'Phosphorsäurebasiertes Mittel zur Rostentfernung von Stahl, Gusseisen, Aluminium und Kupfer.',
    },
    description: {
      en: 'DG Rust Remover is a concentrated acidic liquid based on phosphoric acid and surfactants for removing rust from steel and cast iron. Also removes tarnish from aluminium and copper, and eliminates limescale. Non-flammable. Apply by immersion (2–20 min) or brush. Available as 25 L concentrate.',
      pl: 'DG Rust Remover to skoncentrowany preparat na bazie kwasu fosforowego do usuwania rdzy ze stali i żeliwa. Usuwa też przebarwienia z aluminium i miedzi. Niepalny; zanurzenie 2–20 min lub pędzel. Koncentrat 25 L.',
      de: 'DG Rust Remover ist ein konzentriertes phosphorsäurebasiertes Mittel zur Rostentfernung. Entfernt auch Anlauffarben von Aluminium und Kupfer. Nicht brennbar. Eintauchen 2–20 Min. oder Bürsten.',
    },
    zones: ['engine_room', 'deck'],
    tags: ['rust', 'rust remover', 'phosphoric acid', 'steel', 'limescale', 'corrosion'],
    isBiological: false,
    dosage: { baseConc: 100, unit: 'ml/L', notesEn: 'Immersion 2–20 min or brush; rinse with fresh water.' },
    category: 'Engine Room',
    image: '/products/Rust Remover krzywe_czarna.jpg',
  },
  {
    id: '42', slug: 'separator-cleaner',
    name: { en: 'DG Separator Cleaner', pl: 'DG Separator Cleaner', de: 'DG Separator Cleaner' },
    shortDesc: {
      en: 'Acid-based liquid for cleaning separator discs and bowls, passivating stainless steel.',
      pl: 'Kwaśny preparat do czyszczenia tarcz i mis separatorów, pasywizujący stal nierdzewną.',
      de: 'Säurebasiertes Mittel zur Reinigung von Separatorscheiben, passiviert Edelstahl.',
    },
    description: {
      en: 'DG Separator Cleaner is a powerful acid-based liquid for cleaning separator discs and bowls. Removes carbonised oil and lubricating oil from fuel and lube oil separators; passivates stainless steel. Use undiluted or as 20% solution in fresh water. Soak 30 min to 2 hours; rinse with fresh water jet.',
      pl: 'DG Separator Cleaner to kwasowy preparat do czyszczenia tarcz i mis separatorów. Usuwa zwęglony olej i pasywizuje stal nierdzewną. Stosować nierozcieńczony lub 20% w słodkiej wodzie. Zanurzenie 30 min–2 h.',
      de: 'DG Separator Cleaner ist ein säurebasiertes Mittel zur Reinigung von Separatorscheiben. Entfernt verkohltes Öl, passiviert Edelstahl. 20%-Lösung oder unverdünnt, 30 Min. bis 2 Std. einweichen.',
    },
    zones: ['engine_room'],
    tags: ['separator', 'oil separator', 'fuel oil', 'stainless steel', 'acid', 'lube oil'],
    isBiological: false,
    dosage: { baseConc: 100, unit: 'ml/L', notesEn: 'Undiluted or 20% in fresh water; soak 30 min–2 h.' },
    category: 'Engine Room',
    image: '/products/Separator Cleaner krzywe_czarna.jpg',
  },
  {
    id: '43', slug: 'tankcleaner-plus',
    name: { en: 'DG Tankcleaner Plus', pl: 'DG Tankcleaner Plus', de: 'DG Tankcleaner Plus' },
    shortDesc: {
      en: 'Enhanced emulsifying and degreasing formulation for thorough oil removal from cargo and storage tanks.',
      pl: 'Wzmocniona formulacja emulgująca i odtłuszczająca do gruntownego usuwania olejów ze zbiorników.',
      de: 'Verbesserte Emulgier- und Entfettungsformulierung zur gründlichen Öl-Entfernung aus Tanks.',
    },
    description: {
      en: 'DG Tankcleaner Plus is an enhanced concentrated water-based emulsifying and degreasing formulation for thorough oil and fat removal from cargo and storage tanks. Compatible with steel, plastic, epoxy, and zinc coatings. Use 10–25% solution for machine washing (35–55°C) or undiluted for direct injection.',
      pl: 'DG Tankcleaner Plus to wzmocniona wersja do gruntownego usuwania olejów i tłuszczów ze zbiorników. Kompatybilny ze stalą, plastikiem, powłokami epoksydowymi. Roztwór 10–25% do mycia maszynowego (35–55°C).',
      de: 'DG Tankcleaner Plus ist eine verbesserte wasserbasierte Formulierung zur Entölung von Cargo- und Lagertanks. Kompatibel mit Stahl, Kunststoff und Epoxidbeschichtungen. 10–25% bei 35–55°C.',
    },
    zones: ['cargo_hold', 'ballast_tank'],
    tags: ['tank cleaner', 'cargo tank', 'emulsifier', 'degreaser', 'oil', 'epoxy safe'],
    isBiological: false,
    dosage: { baseConc: 15, unit: '%', notesEn: '10–25% machine washing (35–55°C); undiluted direct injection.' },
    category: 'Cargo Hold',
    image: '/products/Tankcleaner Plus krzywe_niebieska.jpg',
  },
  {
    id: '44', slug: 'tankcleaner',
    name: { en: 'DG Tankcleaner', pl: 'DG Tankcleaner', de: 'DG Tankcleaner' },
    shortDesc: {
      en: 'Concentrated emulsifying and degreasing agent for oil and fat removal from cargo tanks.',
      pl: 'Skoncentrowany środek emulgujący i odtłuszczający do usuwania olejów ze zbiorników ładunkowych.',
      de: 'Konzentriertes Emulgier- und Entfettungsmittel zur Öl-Entfernung aus Cargo-Tanks.',
    },
    description: {
      en: 'DG Tankcleaner is a concentrated water-based emulsifying and degreasing agent based on petroleum solvents and surfactants for oil and fat removal from cargo and storage tanks. Compatible with steel, plastic, epoxy, and zinc coatings. Use 10–25% solution in heated water (35–55°C) for machine washing.',
      pl: 'DG Tankcleaner to skoncentrowany środek emulgujący i odtłuszczający do usuwania olejów i tłuszczów ze zbiorników. Kompatybilny ze stalą i powłokami epoksydowymi. Roztwór 10–25% w 35–55°C do mycia maszynowego.',
      de: 'DG Tankcleaner ist ein konzentriertes wasserbasiertes Emulgier- und Entfettungsmittel für Cargo- und Lagertanks. 10–25% Lösung in erwärmtem Wasser (35–55°C).',
    },
    zones: ['cargo_hold', 'ballast_tank'],
    tags: ['tank cleaner', 'cargo', 'emulsifier', 'petroleum solvent', 'oil', 'surfactant'],
    isBiological: false,
    dosage: { baseConc: 15, unit: '%', notesEn: '10–25% in heated water (35–55°C) for machine washing.' },
    category: 'Cargo Hold',
    image: '/products/Tankcleaner krzywe_niebieska.jpg',
  },
  {
    id: '45', slug: 'ultrasonic-cleaner',
    name: { en: 'DG Ultrasonic Cleaner', pl: 'DG Ultrasonic Cleaner', de: 'DG Ultrasonic Cleaner' },
    shortDesc: {
      en: 'Specialised low-foaming cleaning agent with softening agents for ultrasonic bath cleaning.',
      pl: 'Specjalistyczny niskopienisty środek ze środkami zmiękczającymi do kąpieli ultradźwiękowych.',
      de: 'Spezielles schaumarmes Reinigungsmittel mit Weichmachern für Ultraschallbäder.',
    },
    description: {
      en: 'DG Ultrasonic Cleaner is a specialised low-foaming cleaning agent with softening and complexing agents for use in ultrasonic baths. Free of hydrocarbon solvents. Use as 5–20% solution at 55–75°C; cleaning time 5–30 minutes. Rinse with high-pressure fresh water. Solution can be reused if not heavily contaminated.',
      pl: 'DG Ultrasonic Cleaner to niskopienisty środek do kąpieli ultradźwiękowych ze środkami zmiękczającymi. Stosować 5–20% w 55–75°C, czas 5–30 min. Spłukać wodą wysokociśnieniową. Roztwór można ponownie użyć.',
      de: 'DG Ultrasonic Cleaner ist ein niedrigschäumendes Reinigungsmittel für Ultraschallbäder. 5–20% Lösung bei 55–75°C, Reinigungszeit 5–30 Min. Lösung kann wiederverwendet werden.',
    },
    zones: ['engine_room'],
    tags: ['ultrasonic', 'bath cleaner', 'low foam', 'precision cleaning', 'specialist', 'complexing'],
    isBiological: false,
    dosage: { baseConc: 10, unit: '%', notesEn: '5–20% solution at 55–75°C; cleaning time 5–30 min.' },
    category: 'Engine Room',
    image: '/products/Ultrasonic Cleaner krzywe_niebieska.jpg',
  },
  {
    id: '46', slug: 'vacuum-pipe-cleaner-bioactivae',
    name: { en: 'DG Vacuum Pipe Cleaner BioActivae', pl: 'DG Vacuum Pipe Cleaner BioActivae', de: 'DG Vacuum Pipe Cleaner BioActivae' },
    shortDesc: {
      en: 'Concentrated acidic descaling agent with enzymes for removing scale from vacuum toilet piping.',
      pl: 'Skoncentrowany kwaśny środek z enzymami do usuwania kamienia z próżniowych rurociągów toaletowych.',
      de: 'Konzentrierter saurer Entkalker mit Enzymen für Vakuum-Toilettenrohre.',
    },
    description: {
      en: 'DG Vacuum Pipe Cleaner BioActivae is a concentrated acidic descaling agent with mixed acids and enzymes for removing inorganic scale from vacuum toilet piping. Non-flammable, safe for system materials except galvanised installations. Daily dosage: 1.2–1.4 L per dosing station (approx. 8–10 toilets).',
      pl: 'DG Vacuum Pipe Cleaner BioActivae to skoncentrowany kwaśny środek z enzymami do usuwania kamienia z próżniowych rurociągów toaletowych. Niepalny. Dawka dzienna: 1,2–1,4 L/stację dozującą (ok. 8–10 toalet).',
      de: 'DG Vacuum Pipe Cleaner BioActivae ist ein konzentrierter saurer Entkalker mit Enzymen für Vakuum-Toilettenrohre. Tägliche Dosierung: 1,2–1,4 L pro Dosierstation (ca. 8–10 Toiletten).',
    },
    zones: ['accommodation', 'engine_room'],
    tags: ['vacuum toilet', 'vacuum pipes', 'scale', 'enzyme', 'sanitary', 'biological'],
    isBiological: true,
    dosage: { baseConc: 1.3, unit: 'ml/L', notesEn: 'Daily dose: 1.2–1.4 L per dosing station (8–10 toilets).' },
    category: 'Biological',
    image: '/products/bio/Vacuum BioActivae krzywe_zielony.jpg',
  },
  {
    id: '47', slug: 'vapor-control',
    name: { en: 'DG Vapor Control', pl: 'DG Vapor Control', de: 'DG Vapor Control' },
    shortDesc: {
      en: 'Concentrated polymer for controlling scale and foam in seawater evaporators.',
      pl: 'Skoncentrowany preparat polimerowy do kontrolowania kamienia i piany w wyparnikach.',
      de: 'Konzentriertes Polymerprodukt zur Kontrolle von Kalk und Schaum in Seewasserverdampfern.',
    },
    description: {
      en: 'DG Vapor Control is a safe water-soluble concentrated polymer for controlling scale and foam in seawater evaporators. Prevents scaling, reduces foaming, and maintains optimum evaporator performance. Standard dosage: 25–45 ml per ton of distillate, continuously injected. Available as 25 L concentrate.',
      pl: 'DG Vapor Control to skoncentrowany preparat polimerowy do kontrolowania kamienia i piany w wyparnikach. Zapobiega osadzaniu i utrzymuje optymalną pracę wyparnika. Dawka: 25–45 ml/tonę destylatu.',
      de: 'DG Vapor Control ist ein konzentriertes Polymerprodukt zur Kontrolle von Kalk und Schaum in Seewasserverdampfern. Dosierung: 25–45 ml pro Tonne Destillat, kontinuierlich injiziert.',
    },
    zones: ['engine_room', 'cooling'],
    tags: ['evaporator', 'scale control', 'foam control', 'seawater', 'polymer', 'distillate'],
    isBiological: false,
    dosage: { baseConc: 35, unit: 'ml/L', notesEn: 'Continuously inject 25–45 ml per ton of distillate.' },
    category: 'Engine Room',
    image: '/products/Vapor Control krzywe_biała.jpg',
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return MOCK_PRODUCTS.find(p => p.slug === slug)
}

export function getProductsByZone(zone: ZoneId): Product[] {
  return MOCK_PRODUCTS.filter(p => p.zones.includes(zone))
}
